### ISSUE TITLE
Model build error with csv?  line 26796 did not have 8 elements

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/DIO#8]
Called during build model
https://github.com/USEPA/DIO/blob/dc9e24b2c2eeb88447ad9ab36af00e1205ed9e2d/DIO.Rmd#L39

```
2023-06-23 11:20:42 INFO::Loading hybridization specification file for DIOProcesses...
 Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : 
line 26796 did not have 8 elements
```

**Comment by WesIngwersen** [comment]
@bl-young   I assumed this occurred loading DIO A or B matrices which have that many lines, but i checked and both look fine - i edited to add quotes around one name in that line for the B matrix, but that didn't fix it

**Comment by bl-young** [comment]
ok i'll take a look

**Comment by bl-young** [comment]
Ok I'm remembering now that there were a few minor issues like this that have been fixed on the WIO branch (see for example https://github.com/USEPA/useeior/commit/801f70fdfa50f51d60c86f0664efb12a5edc7b92). So the model can be run on that branch. Which impacts the plan here...

**Comment by bl-young** [comment]
see https://github.com/USEPA/useeior/pull/255 which should resolve this

**Comment by bl-young** [comment]
Working with useeior v1.2.2
